### ISSUE TITLE
Empty per-read and per-site file

### ISSUE THREAD

**Issue by vahidAK** [enovoa/EpiNano#29] opened 2019-11-04 18:18 UTC
Hi @Huanle 

After running per_read_var.py and per_site_var.py scripts the results file are empty?
I exactly followed all the previous step and everything was fine but these two scripts did not give any results.
Thanks,
Vahid.

**Comment by enovoa** [comment] 2019-11-04 19:34
Hi please try with the example data, thank you!

**Comment by Huanle** [comment] 2019-11-05 09:41
Hi @vahidAK ,
if you can send me your input files for these two scripts. 
I will be more likely to figure out and fix your issue.
Thanks for using Epinano and I look forward to any further questions you might have.

**Comment by enovoa** [comment] 2019-11-05 09:58
Hi @vahidAK please first try to use the code with the provided examples in the github, and give detailed feedback on what you see.  thanks!

**Comment by akesarwani** [comment] 2019-11-21 19:40
I am having the same issue of empty output file. The **line number 42** of **assign_current_to_per_read_kmer.py** is trying to get read id and pos from the wrong columns of **output.tsv_per_rd_var.del.adjust.csv**. Actually its column 3 and 4 instead of 1 and 2.

**Comment by Huanle** [comment] 2019-11-22 11:46
hi @akesarwani , can you share with me your input file, perhaps a part of it, for running the scripts?
This way, I can help more.

**Comment by akesarwani** [comment] 2019-11-22 16:23
**event.tbl.features.readposition.adj.csv** - not every line of this file has 4 field. Therefore, the script "assign_current_to_per_read_kmer.py" throws error when tries to split line and  slice array in line number 26-27 of the code: Please see below the input file.

#Read,position,Intensity,Kmer_3_to_5
d075ce84-9324-4e2b-99f2-38eb7b09ed14,70.23893737792969,4.742015361785889,TCCCC,1,0.9141980409622192,TCCCC,0.6105651259422302,0,0,3
d075ce84-9324-4e2b-99f2-38eb7b09ed14 385:386:387:388:389
d075ce84-9324-4e2b-99f2-38eb7b09ed14,385:386:387:388:389,70.23893737792969,TCCCC
d075ce84-9324-4e2b-99f2-38eb7b09ed14,106.32499694824219,8.08000373840332,CCCGG,2,0.9981605410575867,CCCGA,0.31705111265182495,1,0,5
d075ce84-9324-4e2b-99f2-38eb7b09ed14 383:384:385:386:387
d075ce84-9324-4e2b-99f2-38eb7b09ed14,383:384:385:386:387,106.32499694824219,CCCGG
d075ce84-9324-4e2b-99f2-38eb7b09ed14,104.18009185791016,11.277137756347656,CGGAA,2,0.6860183477401733,AAGGC,0.013088935054838657,4,0,7
d075ce84-9324-4e2b-99f2-38eb7b09ed14 381:382:383:384:385
d075ce84-9324-4e2b-99f2-38eb7b09ed14,381:382:383:384:385,104.18009185791016,CGGAA
d075ce84-9324-4e2b-99f2-38eb7b09ed14,103.46204376220703,3.0719776153564453,GAAGG,2,0.8857111930847168,AAGGC,0.1800805777311325,3,0,9
d075ce84-9324-4e2b-99f2-38eb7b09ed14 379:380:381:382:383
d075ce84-9324-4e2b-99f2-38eb7b09ed14,379:380:381:382:383,103.46204376220703,GAAGG
d075ce84-9324-4e2b-99f2-38eb7b09ed14,103.53569793701172,12.123465538024902,AAGGA,1,0.9318995475769043,AAGGA,0.5326278805732727,0,0,10
d075ce84-9324-4e2b-99f2-38eb7b09ed14 378:379:380:381:382
d075ce84-9324-4e2b-99f2-38eb7b09ed14,378:379:380:381:382,103.53569793701172,AAGGA
d075ce84-9324-4e2b-99f2-38eb7b09ed14,102.06280517578125,2.704951286315918,AGGAA,1,0.920275092124939,AAGGA,0.05997687578201294,2,0,11
d075ce84-9324-4e2b-99f2-38eb7b09ed14 377:378:379:380:381
d075ce84-9324-4e2b-99f2-38eb7b09ed14,377:378:379:380:381,102.06280517578125,AGGAA
d075ce84-9324-4e2b-99f2-38eb7b09ed14,110.2466049194336,2.460848569869995,GAAGA,2,0.6915823221206665,GAAGG,0.09732760488986969,1,0,13
d075ce84-9324-4e2b-99f2-38eb7b09ed14 375:376:377:378:379

**Comment by akesarwani** [comment] 2019-11-22 20:22
Could you please check below if the script name and position command-line arguments are correct.

Also, I would like to make sure the documentation of #3 is correct. I am doubtful as when I looked into code the fields you trying to read from previous output file are not in concordance. 

**#3 combine extracted features with per_read and per_site variants information**

python2 fastq_len.py h5t3.fastq > h5t3.fastq.len
python2 adjust_read_base_positions.py  h5t3.fastq.len output.event.tbl.features number_of_chopped_leading_bases number_of_chopped_end_bases > output.event.tbl.features.readposition.adj.csv
python2 assign_current_to_per_read_kmer.py output.event.tbl.features.readposition.adj.csv per_rd_var.del.adjust.csv.summed.oneKmer_oneLine  > per_read.var.current.csv
python2 per_read_kmer_intensity_to_per_site_kmer_intensity.py per_read.var.current.csv per_site.varsliding.win.csv > per_site.var.current.csv

**Comment by Huanle** [comment] 2019-11-24 19:48
@akesarwani , the commands you are using are correct. But can you share with me your input files so that i can examine what gave rise to the warning/problem?

**Comment by akesarwani** [comment] 2019-11-25 15:31
Please see the top few lines from two input files:
sample.event.tbl.features.readposition.adj.csv
#Read,position,Intensity,Kmer_3_to_5
d075ce84-9324-4e2b-99f2-38eb7b09ed14,70.23893737792969,4.742015361785889,TCCCC,1,0.9141980409622192,TCCCC,0.6105651259422302,0,0,3
d075ce84-9324-4e2b-99f2-38eb7b09ed14 385:386:387:388:389
d075ce84-9324-4e2b-99f2-38eb7b09ed14,385:386:387:388:389,70.23893737792969,TCCCC
d075ce84-9324-4e2b-99f2-38eb7b09ed14,106.32499694824219,8.08000373840332,CCCGG,2,0.9981605410575867,CCCGA,0.31705111265182495,1,0,5
d075ce84-9324-4e2b-99f2-38eb7b09ed14 383:384:385:386:387
d075ce84-9324-4e2b-99f2-38eb7b09ed14,383:384:385:386:387,106.32499694824219,CCCGG
d075ce84-9324-4e2b-99f2-38eb7b09ed14,104.18009185791016,11.277137756347656,CGGAA,2,0.6860183477401733,AAGGC,0.013088935054838657,4,0,7
d075ce84-9324-4e2b-99f2-38eb7b09ed14 381:382:383:384:385
d075ce84-9324-4e2b-99f2-38eb7b09ed14,381:382:383:384:385,104.18009185791016,CGGAA

Sample.bam.tsv_per_rd_var.del.adjust.csv
#REF,REF_POS,REF_BASE,READ_NAME,READ_POSITION,READ_BASE,BASE_QUALITY,MISMATCH,INSERTION,DELETION
cc6m_2244_t7_ecorv,1,T,be3d8192-8ec3-4bc5-aa19-accba7bc990d,1,T,5,0,0,0.0
cc6m_2244_t7_ecorv,2,C,be3d8192-8ec3-4bc5-aa19-accba7bc990d,2,C,9,0,0,0.0
cc6m_2244_t7_ecorv,3,C,be3d8192-8ec3-4bc5-aa19-accba7bc990d,3,C,14,0,0,0.0
cc6m_2244_t7_ecorv,4,G,be3d8192-8ec3-4bc5-aa19-accba7bc990d,4,G,8,0,0,0.0
cc6m_2244_t7_ecorv,5,G,be3d8192-8ec3-4bc5-aa19-accba7bc990d,5,G,12,0,0,0.0
cc6m_2244_t7_ecorv,6,C,be3d8192-8ec3-4bc5-aa19-accba7bc990d,6,C,9,0,0,0.0
cc6m_2244_t7_ecorv,7,T,be3d8192-8ec3-4bc5-aa19-accba7bc990d,7,T,9,0,0,0.0
cc6m_2244_t7_ecorv,8,G,be3d8192-8ec3-4bc5-aa19-accba7bc990d,8,G,7,0,0,0.0
cc6m_2244_t7_ecorv,9,T,be3d8192-8ec3-4bc5-aa19-accba7bc990d,9,T,8,0,0,0.0

**Comment by sem0036** [comment] 2019-12-06 20:43
Hello, I am also getting empty per_read files. I tried with the example data and still received empty files.

**Comment by vahidAK** [comment] 2019-12-17 20:15
> Hello, I am also getting empty per_read files. I tried with the example data and still received empty files.

Hi @sem0036 ,

I think you are using the previous version in which you had to manually split data and run all the scripts in order. I used the new version of EpiNano and it worked just fine.

**Comment by Huanle** [comment] 2019-12-21 15:07
@akesarwani ,I can see that the number of columns of your input file varies across lines. this should cause the error message you've seen.
i simple can not tell the why given the limited information.

**Comment by enovoa** [comment] 2019-12-29 18:59
Dear all, please try the new release of Epinano and let us know if you have any issues. As per @vahidAK's comment, this seems to be solved. Thank you!

**Comment by enovoa** [comment] 2020-01-09 23:27
Dear all, I understand that the problem is solved with the new release of EpiNano, so I am closing this issue for the moment. Please reopen the issue if you still have issues with the empty files. Thanks all!

**Closed by enovoa** 2020-01-09 23:27 UTC
